### PR TITLE
Added bower.json, registered package on bower.

### PR DESCRIPTION
**Pull request by falxcerebri**
I think that's it. Now you can just accept this pull request. Your package is on bower and I'm happily using it.

### CODE REVIEW

**Comment by falxcerebri** [comment]
Just for clarity, that's related to #2

**Comment by qrb** [comment]
Thanks @falxcerebri

**Comment by falxcerebri** [comment]
I think that was little too fast. The `bower.json` misses  `dependencies` which should be generated by bower wizard... sorry for the trouble. Pach or another PR?

**Comment by qrb** [comment]
I'm easy. Just create another PR

**Pull request merged**
